[package]
name = "chapter20"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = {version = "1", features = ["unstable"]}
argonautica = "0.2.0"
surf = "2.3.2"